baseURL: "https://www.akinjide.me/"
languageCode: "en-us"
metaDataFormat: "yaml"
title: "Akinjide Bankole"
pygmentsCodeFences: true
pygmentsStyle: "algol_nu"
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
params:
  author: "Akinjide Bankole"
  description: "The personal website of Akinjide Bankole: programmer, speaker and designer."
  email: "r@akinjide.me"
  subtitle: "I'm just smart and I like to code."
  mailchimpFormAction: "https://akinjide.us13.list-manage.com/subscribe/post?u=145be832f9f3713fb2544aed2&amp;id=beb6406ab9"
  googleAnalyticsTrackingId: "UA-64387772-2"
  googleSiteVerification: "ZOJ4Y0ndk1sfmlPBrjCnq_lKy9ix0iJaaj_hEKH4nT0"
  navLinks:
    - title: "GitHub"
      url: "https://github.com/akinjide"
    - title: "Gists"
      url: "https://gist.github.com/akinjide"
    - title: "StackOverflow"
      url: "https://stackoverflow.com/users/6045122/akinjide"
    - title: "GPG Key"
      url: "https://www.akinjide.me/akinjide-pubkey.txt"
    - title: "Email"
      url: "mailto:r@akinjide.me"
author:
  name: "Akinjide Bankole"
  email: "r@akinjide.me"
