baseURL: "https://www.akinjide.me/"
languageCode: "en-us"
metaDataFormat: "yaml"
title: "Akinjide Bankole"
pygmentsCodeFences: true
pygmentsStyle: "bw"
disableKinds:
  - section
  - taxonomy
  - taxonomyTerm
copyright: "2015 - 2022"
rssLimit: 20
params:
  author: "Akinjide Bankole"
  description: "The personal website of Akinjide Bankole: programmer, speaker and designer."
  email: "r@akinjide.me"
  subtitle: "I'm just smart and I like to code."
  googleAnalyticsTrackingId: "UA-64387772-2"
  googleSiteVerification: "ZOJ4Y0ndk1sfmlPBrjCnq_lKy9ix0iJaaj_hEKH4nT0"
  navLinks:
    - title: "GitHub"
      url: "https://github.com/akinjide"
    - title: "StackOverflow"
      url: "https://stackoverflow.com/users/6045122/akinjide"
    - title: "GPG Key"
      url: "https://www.akinjide.me/akinjide-pubkey.txt"
    - title: "Email"
      url: "mailto:r@akinjide.me"
    - title: "RSS"
      url: "https://www.akinjide.me/feed.xml"
    - title: "Buy me a Coffee"
      url: "https://www.buymeacoffee.com/akinjide"
author:
  name: "Akinjide Bankole"
  email: "r@akinjide.me"
outputFormats:
  RSS:
    baseName: "feed"
