name: build-service

on:
  push:
    branches:
      - master

env:
  GO111MODULE: on

jobs:
  build-push:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
          fetch-depth: 0
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_ACCESS_SECRET_KEY }}
          aws-region: us-east-1
          mask-aws-account-id: false
      - uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: '0.96.0'
      - name: install
        run: |
          npm install -g bower
          bower install
      - name: deploy
        run: |
          hugo version
          make deploy
